### ISSUE TITLE
MAD dataset preprocessing feature requests！！！！ Please

### ISSUE THREAD

**Issue by XD-mu** [SCZwangxiao/TSGVs-MM2023#2]
Hello author,
     Can you conveniently provide the Google Cloud Disk or Baidu Cloud Disk link for downloading the MAD dataset?
      I am unable to download the source MAD data set due to network restrictions. 
     Could you please send me a copy of the MAD processed feature data set? Thank you very much!!! 
    

     I would be grateful if you could answer promptly and provide a dataset

**Comment by SCZwangxiao** [comment]
> Hello author, Can you conveniently provide the Google Cloud Disk or Baidu Cloud Disk link for downloading the MAD dataset? I am unable to download the source MAD data set due to network restrictions. Could you please send me a copy of the MAD processed feature data set? Thank you very much!!!
> 
> ```
>  I would be grateful if you could answer promptly and provide a dataset
> ```

Hi, here is the Baidu Cloud Disk [link](https://pan.baidu.com/s/1uEiT7HbCjrrGvfB8SWK08w?pwd=425j) for the MAD features. Note that this is our processed version.
